set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports rst]

set_property IOSTANDARD LVCMOS33 [get_ports {DIG[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DIG[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DIG[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DIG[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DIG[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DIG[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DIG[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DIG[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {R[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {R[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {R[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {R[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {G[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {G[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {G[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {G[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {B[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {B[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {B[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {B[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports VS]
set_property IOSTANDARD LVCMOS33 [get_ports HS]

set_property IOSTANDARD LVCMOS33 [get_ports time_up]
set_property IOSTANDARD LVCMOS33 [get_ports time_pause]
set_property IOSTANDARD LVCMOS33 [get_ports time_go]
set_property IOSTANDARD LVCMOS33 [get_ports time_down]

set_property IOSTANDARD LVCMOS33 [get_ports data_in]
set_property IOSTANDARD LVCMOS33 [get_ports clk_in]


set_property PACKAGE_PIN E3 [get_ports clk]
set_property PACKAGE_PIN N17 [get_ports rst]

set_property PACKAGE_PIN P18 [get_ports time_down]
set_property PACKAGE_PIN M18 [get_ports time_up]
set_property PACKAGE_PIN P17 [get_ports time_go]
set_property PACKAGE_PIN M17 [get_ports time_pause]

set_property PACKAGE_PIN B12 [get_ports VS]
set_property PACKAGE_PIN B11 [get_ports HS]

set_property PACKAGE_PIN F4 [get_ports clk_in]
set_property PACKAGE_PIN B2 [get_ports data_in]

set_property PACKAGE_PIN H15 [get_ports {SEG[7]}]
set_property PACKAGE_PIN L18 [get_ports {SEG[6]}]
set_property PACKAGE_PIN T11 [get_ports {SEG[5]}]
set_property PACKAGE_PIN P15 [get_ports {SEG[4]}]
set_property PACKAGE_PIN K13 [get_ports {SEG[3]}]
set_property PACKAGE_PIN K16 [get_ports {SEG[2]}]
set_property PACKAGE_PIN R10 [get_ports {SEG[1]}]
set_property PACKAGE_PIN T10 [get_ports {SEG[0]}]
set_property PACKAGE_PIN U13 [get_ports {DIG[7]}]
set_property PACKAGE_PIN K2 [get_ports {DIG[6]}]
set_property PACKAGE_PIN T14 [get_ports {DIG[5]}]
set_property PACKAGE_PIN P14 [get_ports {DIG[4]}]
set_property PACKAGE_PIN J14 [get_ports {DIG[3]}]
set_property PACKAGE_PIN T9 [get_ports {DIG[2]}]
set_property PACKAGE_PIN J18 [get_ports {DIG[1]}]
set_property PACKAGE_PIN J17 [get_ports {DIG[0]}]

set_property PACKAGE_PIN A4 [get_ports {R[3]}]
set_property PACKAGE_PIN C5 [get_ports {R[2]}]
set_property PACKAGE_PIN B4 [get_ports {R[1]}]
set_property PACKAGE_PIN A3 [get_ports {R[0]}]
set_property PACKAGE_PIN A6 [get_ports {G[3]}]
set_property PACKAGE_PIN B6 [get_ports {G[2]}]
set_property PACKAGE_PIN A5 [get_ports {G[1]}]
set_property PACKAGE_PIN C6 [get_ports {G[0]}]
set_property PACKAGE_PIN D8 [get_ports {B[3]}]
set_property PACKAGE_PIN D7 [get_ports {B[2]}]
set_property PACKAGE_PIN C7 [get_ports {B[1]}]
set_property PACKAGE_PIN B7 [get_ports {B[0]}]
